import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export { LanguageContext };

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    // Get language from localStorage or default to 'en'
    return localStorage.getItem('app_language') || 'en';
  });

  const translations = {
    en: {
      // Admin Dashboard
      'admin.dashboard': 'Admin Dashboard',
      'admin.categories': 'Categories',
      'admin.areas': 'Areas',
      'admin.governorates': 'Governorates',
      'admin.administrators': 'Administrators',
      'admin.clients': 'Clients',
      'admin.suppliers': 'Suppliers',
      
      // Common
      'common.add': 'Add',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.search': 'Search',
      'common.loading': 'Loading...',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.yes': 'Yes',
      'common.no': 'No',
      'common.confirm': 'Confirm',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.previous': 'Previous',
      'common.submit': 'Submit',
      'common.close': 'Close',
      'common.open': 'Open',
      'common.refresh': 'Refresh',
      'common.export': 'Export',
      'common.import': 'Import',
      'common.download': 'Download',
      'common.upload': 'Upload',
      'common.view': 'View',
      'common.details': 'Details',
      'common.actions': 'Actions',
      'common.status': 'Status',
      'common.name': 'Name',
      'common.email': 'Email',
      'common.phone': 'Phone',
      'common.address': 'Address',
      'common.created_at': 'Created At',
      'common.updated_at': 'Updated At',
      'common.management': 'Management',
      'common.retry': 'Retry',
      'common.user': 'User',
      'common.changes': 'Changes',
      'common.total': 'total',
      'common.showing': 'Showing {from} to {to} of {total}',
      
      // Search
      'search.placeholder': 'Search...',
      
      // Profile
      'profile.failed_to_load': 'Failed to load profile',
      'profile.logout_confirm': 'Are you sure you want to logout?',
      'profile.logout': 'Logout',
      'profile.default_name': 'Administrator',
      'profile.administrator': 'Administrator',
      'profile.super_administrator': 'Super Administrator',
      'profile.it_support': 'IT Support',
      'profile.account_type': 'Account Type',
      'profile.secure_admin_account': 'Secure Admin Account',
      
      // Categories
      'categories.title': 'Categories Management',
      'categories.subtitle': 'Organize products with categories and manage their visibility',
      'categories.add': 'Add Category',
      'categories.edit': 'Edit Category',
      'categories.delete': 'Delete Category',
      'categories.name_en': 'Category Name (English)',
      'categories.name_ar': 'Category Name (Arabic)',
      'categories.icon': 'Icon',
      'categories.icon_required': 'Icon is required',
      'categories.icon_optional': 'Icon (optional)',
      'categories.remove_icon': 'Remove current icon',
      'categories.active_category': 'Active Category',
      'categories.inactive_categories_warning': 'Inactive categories won\'t appear in product listings',
      'categories.no_categories': 'No categories found',
      'categories.get_started': 'Get started by creating your first category',
      'categories.loading': 'Loading categories...',
      'categories.created': 'Category created!',
      'categories.updated': 'Category updated!',
      'categories.deleted': 'Category deleted!',
      'categories.delete_confirm': 'Are you sure you want to delete this category?',
      'categories.delete_warning': 'This action cannot be undone.',
      
      // Areas
      'areas.title': 'Areas Management',
      'areas.subtitle': 'Manage delivery areas and their geographic boundaries',
      'areas.add': 'Add Area',
      'areas.edit': 'Edit Area',
      'areas.delete': 'Delete Area',
      'areas.name': 'Area Name',
      'areas.governorate': 'Governorate',
      'areas.polygon_points': 'Polygon Points',
      'areas.select_governorate': 'Select a governorate to view areas',
      'areas.choose_governorate': 'Choose a governorate from the dropdown above to see its areas',
      'areas.no_areas': 'No areas found',
      'areas.loading': 'Loading areas...',
      'areas.created': 'Area created successfully!',
      'areas.updated': 'Area updated successfully!',
      'areas.deleted': 'Area deleted successfully!',
      'areas.delete_confirm': 'Are you sure you want to delete this area?',
      'areas.delete_warning': 'This action cannot be undone.',
      'areas.search_placeholder': 'Search areas by name or governorate...',
      'areas.all_governorates': 'All Governorates',
      'areas.filter_by_governorate': 'Filter by governorate',
      'areas.table_name': 'Name',
      'areas.table_governorate': 'Governorate',
      'areas.table_polygon_points': 'Polygon Points',
      'areas.table_actions': 'Actions',
      'areas.adding': 'Adding...',
      
      // Form validation
      'validation.required': 'This field is required.',
      'validation.email': 'Please enter a valid email address.',
      'validation.phone': 'Please enter a valid phone number.',
      'validation.min_length': 'Must be at least {min} characters.',
      'validation.max_length': 'Must be less than {max} characters.',
      'validation.password_requirements': 'Password must be at least 8 characters and contain: uppercase letter, lowercase letter, number, and special character.',
      'validation.passwords_not_match': 'Passwords do not match.',
      'validation.positive_number': 'Must be a positive number.',
      'validation.percentage_range': 'Must be between 0-100.',
      'validation.image_required': 'Image is required.',
      'validation.image_type': 'File must be an image.',
      'validation.file_size': 'File must be less than {size}MB.',
      
      // Messages
      'messages.success': 'Success!',
      'messages.error': 'Error!',
      'messages.warning': 'Warning!',
      'messages.info': 'Information',
      'messages.please_fix_errors': 'Please fix the errors in the form.',
      'messages.failed_to_submit': 'Failed to submit',
      'messages.failed_to_load': 'Failed to load data',
      'messages.failed_to_delete': 'Failed to delete',
      'messages.failed_to_update': 'Failed to update',
      'messages.failed_to_create': 'Failed to create',
      'messages.operation_successful': 'Operation completed successfully!',
      'messages.operation_failed': 'Operation failed. Please try again.',
      'messages.confirm_action': 'Are you sure you want to perform this action?',
      'messages.unsaved_changes': 'You have unsaved changes. Are you sure you want to leave?',
      'messages.something_went_wrong': 'Something went wrong while loading this page.',
      'messages.try_adjusting_filters': 'Try adjusting your search or filters',
      'messages.authentication_missing': 'Authentication token is missing',
      'messages.showing': 'Showing {from} to {to} of {total}',
      
      // Navigation
      'nav.dashboard': 'Dashboard',
      'nav.categories': 'Categories',
      'nav.areas': 'Areas',
      'nav.governorates': 'Governorates',
      'nav.administrators': 'Administrators',
      'nav.clients': 'Clients',
      'nav.suppliers': 'Suppliers',
      'nav.settings': 'Settings',
      'nav.profile': 'Profile',
      'nav.logout': 'Logout',
      
      // Administrators
      'administrators.title': 'Administrators Management',
      'administrators.subtitle': 'Manage system administrators and their permissions',
      'administrators.add': 'Add New Administrator',
      'administrators.edit': 'Edit Administrator',
      'administrators.delete': 'Delete Administrator',
      'administrators.manage': 'Manage Administrators',
      'administrators.role': 'Role',
      'administrators.superadmin': 'Super Admin',
      'administrators.admin': 'Admin',
      'administrators.loading': 'Loading administrators...',
      'administrators.no_administrators': 'No administrators found',
      'administrators.get_started': 'Get started by adding your first administrator',
      'administrators.add_administrator': '+ Add Administrator',
      'administrators.delete_confirm': 'Delete admin {name}?',
      'administrators.created': 'Administrator created',
      'administrators.updated': 'Administrator updated',
      'administrators.deleted': 'Administrator deleted',
      
      // Suppliers
      'suppliers.title': 'Suppliers Management',
      'suppliers.subtitle': 'Manage supplier accounts and their status',
      'suppliers.search_placeholder': 'Search suppliers by name, email, or phone...',
      'suppliers.all_statuses': 'All Statuses',
      'suppliers.pending': 'Pending',
      'suppliers.rejected': 'Rejected',
      'suppliers.approve': 'Approve',
      'suppliers.reject': 'Reject',
      'suppliers.toggle_status': 'Toggle Status',
      'suppliers.verify_email': 'Verify Email',
      'suppliers.loading': 'Loading suppliers...',
      'suppliers.no_suppliers': 'No suppliers found',
      'suppliers.no_matches': 'No suppliers match your current filters',
      'suppliers.approved': 'Supplier approved successfully',
      'suppliers.rejected_success': 'Supplier rejected successfully',
      'suppliers.status_toggled': 'Supplier status toggled successfully',
      'suppliers.email_verified': 'Supplier email verified successfully',
      'suppliers.deleted': 'Supplier deleted successfully',
      'suppliers.approve_confirm': 'Are you sure you want to approve {name}?',
      'suppliers.reject_confirm': 'Are you sure you want to reject {name}?',
      'suppliers.delete_confirm': 'Are you sure you want to delete {name}? This action cannot be undone.',
      'suppliers.toggle_confirm': 'Are you sure you want to {action} {name}?',
      'suppliers.activate': 'activate',
      'suppliers.deactivate': 'deactivate',
      'suppliers.showing': 'Showing {from} to {to} of {total} suppliers',
      'suppliers.page': 'Page {current} of {total}',
      'suppliers.per_page': 'per page',
      
      // Subscriptions Management
      'subscriptions.title': 'إدارة الاشتراكات',
      'subscriptions.subtitle': 'إدارة اشتراكات الموردين ودورات الفوترة',
      'subscriptions.add': 'إضافة اشتراك',
      'subscriptions.edit': 'تعديل الاشتراك',
      'subscriptions.create': 'إنشاء اشتراك جديد',
      'subscriptions.update': 'تحديث الاشتراك',
      'subscriptions.cancel': 'إلغاء الاشتراك',
      'subscriptions.reactivate': 'إعادة تفعيل الاشتراك',
      'subscriptions.extend': 'تمديد الاشتراك',
      'subscriptions.delete': 'حذف الاشتراك',
      'subscriptions.supplier': 'المورد',
      'subscriptions.plan': 'الخطة',
      'subscriptions.start_date': 'تاريخ البداية',
      'subscriptions.end_date': 'تاريخ الانتهاء',
      'subscriptions.price_per_month': 'السعر شهرياً',
      'subscriptions.months': 'عدد الأشهر',
      'subscriptions.status': 'الحالة',
      'subscriptions.requested_date': 'تاريخ الطلب',
      'subscriptions.actions': 'الإجراءات',
      'subscriptions.total': 'إجمالي الاشتراكات',
      'subscriptions.active': 'نشط',
      'subscriptions.expired': 'منتهي الصلاحية',
      'subscriptions.cancelled': 'ملغي',
      'subscriptions.inactive': 'غير نشط',
      'subscriptions.monthly_revenue': 'الإيرادات الشهرية',
      'subscriptions.all_subscriptions': 'جميع الاشتراكات',
      'subscriptions.pending': 'في الانتظار',
      'subscriptions.approved': 'موافق عليه',
      'subscriptions.rejected': 'مرفوض',
      'subscriptions.search_placeholder': 'البحث في الاشتراكات بالمورد أو الخطة أو البريد الإلكتروني...',
      'subscriptions.loading': 'جاري تحميل الاشتراكات...',
      'subscriptions.loading_suppliers_plans': 'جاري تحميل الموردين والخطط...',
      'subscriptions.no_subscriptions': 'لم يتم العثور على اشتراكات',
      'subscriptions.no_matches': 'لا توجد اشتراكات تطابق المرشحات الحالية',
      'subscriptions.get_started': 'ابدأ بإدارة اشتراكات الموردين',
      'subscriptions.tip': 'نصيحة: تسمح لك الاشتراكات بإدارة وصول الموردين إلى المنصة وتتبع دورات الفوترة بفعالية.',
      'subscriptions.created': 'تم إنشاء الاشتراك بنجاح',
      'subscriptions.updated': 'تم تحديث الاشتراك بنجاح',
      'subscriptions.cancelled_success': 'تم إلغاء الاشتراك بنجاح',
      'subscriptions.reactivated': 'تم إعادة تفعيل الاشتراك بنجاح',
      'subscriptions.extended': 'تم تمديد الاشتراك بنجاح',
      'subscriptions.deleted': 'تم حذف الاشتراك بنجاح',
      'subscriptions.cancel_confirm': 'هل أنت متأكد من إلغاء هذا الاشتراك؟',
      'subscriptions.reactivate_confirm': 'هل أنت متأكد من إعادة تفعيل هذا الاشتراك؟',
      'subscriptions.delete_confirm': 'هل أنت متأكد من حذف هذا الاشتراك؟ لا يمكن التراجع عن هذا الإجراء.',
      'subscriptions.extend_confirm': 'هل أنت متأكد من تمديد هذا الاشتراك؟',
      'subscriptions.select_supplier': 'اختر مورداً',
      'subscriptions.select_plan': 'اختر خطة',
      'subscriptions.subscription_details': 'تفاصيل الاشتراك',
      'subscriptions.date_and_duration': 'التاريخ والمدة',
      'subscriptions.pricing': 'التسعير',
      'subscriptions.months_required': 'عدد الأشهر مطلوب',
      'subscriptions.supplier_required': 'المورد مطلوب',
      'subscriptions.plan_required': 'الخطة مطلوبة',
      'subscriptions.start_date_required': 'تاريخ البداية مطلوب',
      'subscriptions.end_date_required': 'تاريخ الانتهاء مطلوب',
      'subscriptions.price_required': 'السعر الصحيح مطلوب',
      'subscriptions.end_date_after_start': 'تاريخ الانتهاء يجب أن يكون بعد تاريخ البداية',
      'subscriptions.already_approved': 'موافق عليه مسبقاً',
      'subscriptions.already_rejected': 'مرفوض مسبقاً',
      'subscriptions.already_cancelled': 'ملغي مسبقاً',
      'subscriptions.showing': 'عرض {from} إلى {to} من {total} اشتراك',
      'subscriptions.create_description': 'إنشاء اشتراك جديد للمورد',
      'subscriptions.update_description': 'تحديث تفاصيل وإعدادات الاشتراك',
      
      // Plans Management
      'plans.title': 'إدارة الخطط',
      'plans.subtitle': 'إنشاء وإدارة خطط الاشتراك للموردين',
      'plans.add': 'إضافة خطة',
      'plans.edit': 'تعديل الخطة',
      'plans.create': 'إنشاء خطة جديدة',
      'plans.update': 'تحديث الخطة',
      'plans.delete': 'حذف الخطة',
      'plans.name': 'اسم الخطة',
      'plans.name_ar': 'اسم الخطة (العربية)',
      'plans.description': 'الوصف',
      'plans.description_ar': 'الوصف (العربية)',
      'plans.max_clients': 'الحد الأقصى للعملاء',
      'plans.price_per_month': 'السعر شهرياً',
      'plans.is_custom': 'خطة مخصصة',
      'plans.is_active': 'خطة نشطة',
      'plans.standard': 'قياسية',
      'plans.custom': 'مخصصة',
      'plans.all_plans': 'جميع الخطط',
      'plans.search_placeholder': 'البحث في الخطط بالاسم...',
      'plans.loading': 'جاري تحميل الخطط...',
      'plans.no_plans': 'لم يتم العثور على خطط',
      'plans.no_matches': 'لا توجد خطط تطابق المرشحات الحالية',
      'plans.get_started': 'ابدأ بإدارة خطط الاشتراك',
      'plans.created': 'تم إنشاء الخطة بنجاح',
      'plans.updated': 'تم تحديث الخطة بنجاح',
      'plans.deleted': 'تم حذف الخطة بنجاح',
      'plans.delete_confirm': 'هل أنت متأكد من حذف هذه الخطة؟',
      'plans.delete_warning': 'لا يمكن التراجع عن هذا الإجراء.',
      'plans.name_required': 'اسم الخطة مطلوب',
      'plans.name_ar_required': 'اسم الخطة بالعربية مطلوب',
      'plans.price_required': 'السعر الصحيح مطلوب',
      'plans.max_clients_min': 'الحد الأقصى للعملاء يجب أن يكون 1 على الأقل',
      'plans.plan_details': 'تفاصيل الخطة',
      'plans.plan_settings': 'إعدادات الخطة',
      'plans.total_plans': 'إجمالي الخطط',
      'plans.active_plans': 'الخطط النشطة',
      'plans.standard_plans': 'الخطط القياسية',
      'plans.custom_plans': 'الخطط المخصصة',
      'plans.total_revenue': 'إجمالي الإيرادات',
      
      // Subscription Requests
      'requests.title': 'طلبات الاشتراك',
      'requests.subtitle': 'مراجعة وإدارة طلبات الاشتراك من الموردين',
      'requests.approve': 'موافقة',
      'requests.reject': 'رفض',
      'requests.approve_request': 'موافقة على الطلب',
      'requests.reject_request': 'رفض الطلب',
      'requests.all_requests': 'جميع الطلبات',
      'requests.search_placeholder': 'البحث في الطلبات بالمورد أو الخطة أو البريد الإلكتروني...',
      'requests.loading': 'جاري تحميل الطلبات...',
      'requests.no_requests': 'لم يتم العثور على طلبات اشتراك',
      'requests.no_matches': 'لا توجد طلبات تطابق المرشحات الحالية',
      'requests.get_started': 'عندما يطلب الموردون اشتراكات، ستظهر هنا لمراجعتها والموافقة عليها.',
      'requests.approved_success': 'تمت الموافقة على طلب الاشتراك بنجاح',
      'requests.rejected_success': 'تم رفض طلب الاشتراك بنجاح',
      'requests.approve_confirm': 'هل أنت متأكد من الموافقة على طلب الاشتراك لـ "{name}"؟',
      'requests.reject_confirm': 'هل أنت متأكد من رفض طلب الاشتراك لـ "{name}"؟ لا يمكن التراجع عن هذا الإجراء.',
      'requests.total_requests': 'إجمالي الطلبات',
      'requests.today': 'اليوم',
      'requests.standard_plan': 'خطة قياسية',
      'requests.custom_plan': 'خطة مخصصة',
      
      // Supplier Subscriptions
      'supplier_subscriptions.title': 'إدارة الاشتراكات',
      'supplier_subscriptions.subtitle': 'إدارة خطط الاشتراك والطلبات الخاصة بك',
      'supplier_subscriptions.current_subscription': 'الاشتراك الحالي',
      'supplier_subscriptions.available_plans': 'الخطط المتاحة',
      'supplier_subscriptions.subscription_requests': 'طلبات الاشتراك',
      'supplier_subscriptions.current_status': 'الحالة الحالية',
      'supplier_subscriptions.current_plan': 'الخطة الحالية',
      'supplier_subscriptions.monthly_price': 'السعر الشهري',
      'supplier_subscriptions.per_month': 'شهرياً',
      'supplier_subscriptions.subscription_details_description': 'عرض تفاصيل وحالة اشتراكك الحالي',
      'supplier_subscriptions.plans_description': 'تصفح خطط الاشتراك المتاحة وميزاتها',
      'supplier_subscriptions.requests_description': 'إنشاء وإدارة طلبات الاشتراك الخاصة بك',
      'supplier_subscriptions.no_active_subscription': 'لا يوجد اشتراك نشط',
      'supplier_subscriptions.no_subscription_description': 'ليس لديك اشتراك نشط حالياً. تصفح الخطط المتاحة للبدء.',
      'supplier_subscriptions.browse_plans': 'تصفح الخطط',
      'supplier_subscriptions.no_plan': 'لا توجد خطة',
      'supplier_subscriptions.detailed_information': 'معلومات مفصلة',
      'supplier_subscriptions.subscription_id': 'معرف الاشتراك',
      'supplier_subscriptions.duration': 'المدة',
      'supplier_subscriptions.plan_details': 'تفاصيل الخطة',
      'supplier_subscriptions.plan_name': 'اسم الخطة',
      'supplier_subscriptions.total_cost': 'التكلفة الإجمالية',
      'supplier_subscriptions.plan_description': 'وصف الخطة',
      'supplier_subscriptions.browse_other_plans': 'تصفح خطط أخرى',
      'supplier_subscriptions.request_renewal': 'طلب التجديد',
      'supplier_subscriptions.no_plans_available': 'لا توجد خطط متاحة',
      'supplier_subscriptions.no_plans_description': 'لا توجد خطط اشتراك متاحة حالياً.',
      'supplier_subscriptions.custom_plan': 'خطة مخصصة',
      'supplier_subscriptions.view_details': 'عرض التفاصيل',
      'supplier_subscriptions.description': 'الوصف',
      'supplier_subscriptions.features': 'الميزات',
      'supplier_subscriptions.full_platform_access': 'الوصول الكامل للمنصة',
      'supplier_subscriptions.priority_support': 'الدعم ذو الأولوية',
      'supplier_subscriptions.request_subscription': 'طلب الاشتراك',
      'supplier_subscriptions.create_subscription_request': 'إنشاء طلب اشتراك',
      'supplier_subscriptions.select_plan': 'اختر الخطة',
      'supplier_subscriptions.choose_plan': 'اختر خطة',
      'supplier_subscriptions.months_requested': 'الأشهر المطلوبة',
      'supplier_subscriptions.payment_proof': 'إثبات الدفع',
      'supplier_subscriptions.upload_payment_proof': 'رفع إثبات الدفع',
      'supplier_subscriptions.payment_proof_help': 'ارفع لقطة شاشة أو PDF لتأكيد الدفع',
      'supplier_subscriptions.calculated_price': 'السعر المحسوب',
      'supplier_subscriptions.price_breakdown': '${monthly} × {months} أشهر',
      'supplier_subscriptions.submit_request': 'إرسال الطلب',
      'supplier_subscriptions.request_created_success': 'تم إنشاء طلب الاشتراك بنجاح',
      'supplier_subscriptions.pending_request_warning': 'لديك طلب معلق',
      'supplier_subscriptions.pending_request_description': 'لديك بالفعل طلب اشتراك معلق للموافقة. يرجى الانتظار لمراجعة المدير.',
      'supplier_subscriptions.no_requests': 'لا توجد طلبات',
      'supplier_subscriptions.no_requests_description': 'لم تقم بإنشاء أي طلبات اشتراك بعد.',
      'supplier_subscriptions.create_first_request': 'إنشاء أول طلب',
      'supplier_subscriptions.create_request': 'إنشاء طلب',
      'supplier_subscriptions.unknown_plan': 'خطة غير معروفة',
      'supplier_subscriptions.requested_for': 'مطلوب لـ',
      'supplier_subscriptions.request_details': 'تفاصيل الطلب',
      'supplier_subscriptions.request_information': 'معلومات الطلب',
      'supplier_subscriptions.request_id': 'معرف الطلب',
      'supplier_subscriptions.total_amount': 'المبلغ الإجمالي',
      'supplier_subscriptions.view_payment_proof': 'عرض إثبات الدفع',
      'supplier_subscriptions.admin_notes': 'ملاحظات المدير',
      'supplier_subscriptions.plan_required': 'يرجى اختيار خطة',
      'supplier_subscriptions.months_required': 'يرجى إدخال عدد الأشهر',
      'supplier_subscriptions.payment_proof_required': 'يرجى رفع إثبات الدفع',
      'supplier_subscriptions.status': 'الحالة',
      'supplier_subscriptions.status_active': 'نشط',
      'supplier_subscriptions.status_expired': 'منتهي الصلاحية',
      'supplier_subscriptions.status_cancelled': 'ملغي',
      'supplier_subscriptions.status_pending': 'معلق',
      'supplier_subscriptions.status_undefined': 'غير محدد',
      'supplier_subscriptions.start_date': 'تاريخ البداية',
      'supplier_subscriptions.end_date': 'تاريخ الانتهاء',
      'supplier_subscriptions.remaining_days': 'الأيام المتبقية',
      'supplier_subscriptions.days': 'أيام',
      'supplier_subscriptions.current_clients': 'العملاء الحاليون',
      'supplier_subscriptions.remaining_slots': 'الفتحات المتبقية',
      'supplier_subscriptions.price_per_month': 'السعر الشهري',
      'supplier_subscriptions.max_clients': 'الحد الأقصى للعملاء',
      
      // Governorates
      'governorates.title': 'Governorates',
      'governorates.subtitle': 'View all available governorates in the system',
      'governorates.view': 'View',
      'governorates.all_governorates': 'All Governorates',
      'governorates.count': '{count} governorate{plural}',
      'governorates.loading': 'Loading governorates...',
      'governorates.no_governorates': 'No governorates found',
      'governorates.id': 'ID',
      
      // Form Fields
      'form.full_name': 'Full Name',
      'form.email_address': 'Email Address',
      'form.phone_number': 'Phone Number',
      'form.password': 'Password',
      'form.confirm_password': 'Confirm Password',
      'form.role': 'Role',
      'form.select_role': 'Select a role',
      'form.active_account': 'Active Account',
      'form.required': 'Required',
      'form.optional': 'Optional',
      
      // Form Validation Messages
      'form.name_required': 'Name is required.',
      'form.name_min_length': 'Name must be at least 2 characters.',
      'form.name_max_length': 'Name must be less than 50 characters.',
      'form.email_required': 'Email is required.',
      'form.email_invalid': 'Please enter a valid email address.',
      'form.phone_required': 'Phone number is required.',
      'form.phone_invalid': 'Please enter a valid phone number.',
      'form.password_required': 'Password is required.',
      'form.password_requirements': 'Password must be at least 8 characters and contain: uppercase letter, lowercase letter, number, and special character.',
      'form.confirm_password_required': 'Password confirmation is required.',
      'form.passwords_not_match': 'Passwords do not match.',
      'form.role_required': 'Role is required.',
      
      // Form Placeholders
      'form.placeholder.full_name': 'Enter administrator\'s full name',
      'form.placeholder.email': 'Enter email address',
      'form.placeholder.phone': 'Enter phone number (e.g., 01234567890)',
      'form.placeholder.password': 'Enter secure password',
      'form.placeholder.confirm_password': 'Confirm your password',
      'form.placeholder.category_name_en': 'Enter category name in English',
      'form.placeholder.category_name_ar': 'أدخل اسم الفئة بالعربية',
      'form.placeholder.area_name': 'Enter area name',
      
      // Form Actions
      'form.cancel': 'Cancel',
      'form.create': 'Create',
      'form.update': 'Update',
      'form.save': 'Save',
      'form.show_password': 'Show password',
      'form.hide_password': 'Hide password',
      
      // Modal Titles
      'modal.add_administrator': 'Add New Administrator',
      'modal.edit_administrator': 'Edit Administrator',
      'modal.add_category': 'Add New Category',
      'modal.edit_category': 'Edit Category',
      'modal.add_area': 'Add New Area',
      'modal.edit_area': 'Edit Area',
      
      // Language
      'language.switch': 'Switch Language',
      
      // Login
      'login.admin_title': 'Admin Login',
      'login.subtitle': 'Access the administrative dashboard',
      'login.email_label': 'Email Address *',
      'login.password_label': 'Password *',
      'login.email_placeholder': 'Enter your email address',
      'login.password_placeholder': 'Enter your password',
      'login.sign_in': 'Sign In',
      'login.signing_in': 'Signing In...',
      'login.need_help': 'Need help? Contact your system administrator',
      'login.secure_access': 'Secure Admin Access',
      'login.show_password': 'Show password',
      'login.hide_password': 'Hide password',
      'login.email_required': 'Email is required.',
      'login.email_invalid': 'Please enter a valid email address.',
      'login.password_required': 'Password is required.',
      'login.password_min_length': 'Password must be at least 6 characters.',
      'login.login_successful': 'Login successful! Welcome back!',
      'login.login_failed': 'Login failed. Please check your credentials.',
      
      // Supplier Authentication
      'supplier_auth.login_title': 'Supplier Login',
      'supplier_auth.register_title': 'Supplier Registration',
      'supplier_auth.forgot_password_title': 'Forgot Password',
      'supplier_auth.reset_password_title': 'Reset Password',
      'supplier_auth.verify_title': 'Verify Your Supplier Account',
      'supplier_auth.email_or_phone': 'Email or Phone',
      'supplier_auth.email_or_phone_placeholder': 'Enter your email or phone',
      'supplier_auth.password': 'Password',
      'supplier_auth.password_placeholder': 'Enter your password',
      'supplier_auth.confirm_password': 'Confirm Password',
      'supplier_auth.confirm_password_placeholder': 'Confirm password',
      'supplier_auth.new_password': 'New Password',
      'supplier_auth.new_password_placeholder': 'Enter new password',
      'supplier_auth.confirm_new_password': 'Confirm Password',
      'supplier_auth.confirm_new_password_placeholder': 'Confirm new password',
      'supplier_auth.reset_code': 'Reset Code',
      'supplier_auth.reset_code_placeholder': 'Enter reset code',
      'supplier_auth.verification_code': 'Verification Code',
      'supplier_auth.verification_code_placeholder': 'Enter the code you received',
      'supplier_auth.email_address': 'Email Address',
      'supplier_auth.email_placeholder': 'Enter your email address',
      'supplier_auth.name': 'Name',
      'supplier_auth.name_placeholder': 'Supplier name',
      'supplier_auth.name_ar': 'Name (Arabic)',
      'supplier_auth.name_ar_placeholder': 'Supplier name in Arabic',
      'supplier_auth.email': 'Email',
      'supplier_auth.email_placeholder_register': 'Supplier email',
      'supplier_auth.phone': 'Phone',
      'supplier_auth.phone_placeholder': 'Supplier phone',
      'supplier_auth.whatsapp': 'WhatsApp',
      'supplier_auth.whatsapp_placeholder': 'Supplier WhatsApp',
      'supplier_auth.tax_card_number': 'Tax Card Number',
      'supplier_auth.tax_card_number_placeholder': 'Tax card number',
      'supplier_auth.cr_number': 'CR Number',
      'supplier_auth.cr_number_placeholder': 'CR number',
      'supplier_auth.category': 'Category',
      'supplier_auth.select_category': 'Select Category',
      'supplier_auth.loading_categories': 'Loading categories...',
      'supplier_auth.key_persons': 'Key Persons',
      'supplier_auth.key_person_name': 'Name',
      'supplier_auth.key_person_role': 'Role',
      'supplier_auth.key_person_phone': 'Phone',
      'supplier_auth.key_person_email': 'Email',
      'supplier_auth.select_role': 'Select Role',
      'supplier_auth.management': 'Management',
      'supplier_auth.accounting': 'Accounting',
      'supplier_auth.owner': 'Owner',
      'supplier_auth.logo': 'Logo',
      'supplier_auth.tax_card_file': 'Tax Card File',
      'supplier_auth.cr_file': 'CR File',
      'supplier_auth.latitude': 'Latitude',
      'supplier_auth.longitude': 'Longitude',
      'supplier_auth.latitude_placeholder': 'Latitude will be auto-detected',
      'supplier_auth.longitude_placeholder': 'Longitude will be auto-detected',
      'supplier_auth.get_location': 'Get current location',
      'supplier_auth.forgot_password_link': 'Forgot Password?',
      'supplier_auth.register_link': 'Register',
      'supplier_auth.back_to_login': 'Back to Login',
      'supplier_auth.login_button': 'Login',
      'supplier_auth.logging_in': 'Logging in...',
      'supplier_auth.register_button': 'Register',
      'supplier_auth.registering': 'Registering...',
      'supplier_auth.send_reset_link': 'Send Reset Link',
      'supplier_auth.sending': 'Sending...',
      'supplier_auth.reset_password_button': 'Reset Password',
      'supplier_auth.resetting': 'Resetting...',
      'supplier_auth.verify_button': 'Verify',
      'supplier_auth.verifying': 'Verifying...',
      'supplier_auth.resend_code': 'Resend Verification Code',
      'supplier_auth.resending': 'Resending...',
      'supplier_auth.forgot_password_description': 'Enter your email address and we\'ll send you a link to reset your password.',
      'supplier_auth.reset_password_description': 'Enter the reset code sent to your email and your new password.',
      'supplier_auth.password_requirements': 'Password must be at least 8 characters with uppercase, lowercase, and symbol',
      'supplier_auth.login_successful': 'Login successful!',
      'supplier_auth.register_successful': 'Supplier registered successfully!',
      'supplier_auth.reset_link_sent': 'Password reset link sent!',
      'supplier_auth.reset_successful': 'Password reset successful!',
      'supplier_auth.verification_successful': 'Verification successful!',
      'supplier_auth.code_resent': 'Verification code resent!',
      'supplier_auth.login_failed': 'Login failed',
      'supplier_auth.register_failed': 'Registration failed',
      'supplier_auth.reset_link_failed': 'Failed to send reset link',
      'supplier_auth.reset_failed': 'Failed to reset password',
      'supplier_auth.verification_failed': 'Verification failed',
      'supplier_auth.code_required': 'Reset code is required',
      'supplier_auth.password_confirmation_mismatch': 'Password confirmation does not match',
      'supplier_auth.password_min_length': 'Password must be at least 8 characters long',
      'supplier_auth.password_uppercase': 'Password must contain at least one uppercase letter',
      'supplier_auth.password_lowercase': 'Password must contain at least one lowercase letter',
      'supplier_auth.password_symbol': 'Password must contain at least one symbol',
      'supplier_auth.email_required': 'Email is required.',
      'supplier_auth.email_invalid': 'Invalid email format.',
      'supplier_auth.name_ar_required': 'Supplier name in Arabic is required.',
      'supplier_auth.phone_required': 'Phone is required.',
      'supplier_auth.phone_invalid': 'Invalid phone number.',
      'supplier_auth.password_required': 'Password is required.',
      'supplier_auth.password_min_6': 'Password must be at least 6 characters.',
      'supplier_auth.confirm_password_required': 'Please confirm your password.',
      'supplier_auth.passwords_not_match': 'Passwords do not match.',
      'supplier_auth.tax_card_required': 'Tax card number is required.',
      'supplier_auth.cr_number_required': 'CR number is required.',
      'supplier_auth.category_required': 'Category is required.',
      'supplier_auth.logo_required': 'This file is required.',
      'supplier_auth.logo_image': 'Logo must be an image.',
      'supplier_auth.file_image_pdf': 'File must be an image or PDF.',
      'supplier_auth.file_size': 'File must be less than 2MB.',
      'supplier_auth.key_person_required': 'Required.',
      'supplier_auth.key_person_email_invalid': 'Invalid email.',
      'supplier_auth.key_person_phone_invalid': 'Invalid phone.',
      'supplier_auth.failed_load_categories': 'Failed to load categories',
      
      // Client Authentication
      'client_auth.verify_title': 'Verify Your Account',
      'client_auth.email_or_phone': 'Email or Phone',
      'client_auth.email_or_phone_placeholder': 'Enter your email or phone',
      'client_auth.verification_code': 'Verification Code',
      'client_auth.verification_code_placeholder': 'Enter the code you received',
      'client_auth.verify_button': 'Verify',
      'client_auth.verifying': 'Verifying...',
      'client_auth.resend_code': 'Resend Verification Code',
      'client_auth.resending': 'Resending...',
      'client_auth.verification_successful': 'Verification successful!',
      'client_auth.verification_failed': 'Verification failed',
      'client_auth.code_resent': 'Verification code resent!',
      'client_auth.login_title': 'Client Login',
      'client_auth.password': 'Password',
      'client_auth.password_placeholder': 'Enter your password',
      'client_auth.show_password': 'Show password',
      'client_auth.hide_password': 'Hide password',
      'client_auth.forgot_password': 'Forgot Password?',
      'client_auth.login_button': 'Login',
      'client_auth.logging_in': 'Logging in...',
      'client_auth.login_successful': 'Login successful!',
      'client_auth.login_failed': 'Login failed',
      'client_auth.invitation_accepted': 'Invitation accepted successfully!',
      'client_auth.invitation_failed': 'Failed to accept invitation',
      'client_auth.invitation_invalid_expired': 'This invitation link is invalid or has expired. Please contact the supplier for a new invitation.',
      'client_auth.invitation_detected': 'Invitation detected!',
      'client_auth.invitation_auto_accept': 'After login, your invitation will be automatically accepted.',
      'client_auth.forgot_password_title': 'Forgot Password',
      'client_auth.forgot_password_description': 'Enter your email address and we\'ll send you a link to reset your password.',
      'client_auth.email_address': 'Email Address',
      'client_auth.email_placeholder': 'Enter your email address',
      'client_auth.email': 'Email',
      'client_auth.phone': 'Phone Number',
      'client_auth.whatsapp': 'WhatsApp Number',
      'client_auth.tax_card_number': 'Tax Card Number',
      'client_auth.tax_card_file': 'Tax Card File',
      'client_auth.cr_number': 'Commercial Registration Number',
      'client_auth.cr_file': 'Commercial Registration File',
      'client_auth.latitude': 'Latitude',
      'client_auth.longitude': 'Longitude',
      'client_auth.get_location': 'Get current location',
      'client_auth.send_reset_link': 'Send Reset Link',
      'client_auth.sending': 'Sending...',
      'client_auth.reset_link_sent': 'Password reset link sent!',
      'client_auth.reset_link_failed': 'Failed to send reset link',
      'client_auth.back_to_login': 'Back to Login',
      'client_auth.register_title': 'Client Registration',
      'client_auth.client_name': 'Client Name',
      'client_auth.client_name_placeholder': 'Enter client name',
      'client_auth.phone_placeholder': 'Enter your phone number',
      'client_auth.whatsapp_placeholder': 'Enter your WhatsApp number',
      'client_auth.confirm_password': 'Confirm Password',
      'client_auth.confirm_password_placeholder': 'Confirm password',
      'client_auth.tax_card_number_placeholder': 'Enter tax card number',
      'client_auth.cr_number_placeholder': 'Enter commercial registration number',
      'client_auth.latitude_placeholder': 'Latitude will be auto-detected',
      'client_auth.longitude_placeholder': 'Longitude will be auto-detected',
      'client_auth.area_id': 'Area ID',
      'client_auth.area_id_placeholder': 'Enter area ID',
      'client_auth.registering': 'Registering...',
      'client_auth.register_button': 'Register',
      'client_auth.register_successful': 'Registration successful!',
      'client_auth.register_failed': 'Registration failed',
      'client_auth.passwords_not_match': 'Passwords do not match',
      'client_auth.reset_password_title': 'Reset Password',
      'client_auth.reset_password_description': 'Enter the reset code sent to your email and your new password.',
      'client_auth.reset_code': 'Reset Code',
      'client_auth.reset_code_placeholder': 'Enter reset code',
      'client_auth.new_password': 'New Password',
      'client_auth.new_password_placeholder': 'Enter new password',
      'client_auth.confirm_new_password': 'Confirm Password',
      'client_auth.confirm_new_password_placeholder': 'Confirm new password',
      'client_auth.password_requirements': 'Password must be at least 8 characters with uppercase, lowercase, and symbol',
      'client_auth.reset_password_button': 'Reset Password',
      'client_auth.resetting': 'Resetting...',
      'client_auth.reset_successful': 'Password reset successful!',
      'client_auth.reset_failed': 'Failed to reset password',
      'client_auth.reset_code_required': 'Reset code is required',
      'client_auth.password_confirmation_mismatch': 'Password confirmation does not match',
      'client_auth.password_min_length': 'Password must be at least 8 characters long',
      'client_auth.password_uppercase': 'Password must contain at least one uppercase letter',
      'client_auth.password_lowercase': 'Password must contain at least one lowercase letter',
      'client_auth.password_symbol': 'Password must contain at least one symbol',
      
      // Language
      'language.switch_to_english': 'Switch to English',
      'language.switch_to_arabic': 'Switch to Arabic',
      
      // File Upload
      'file_upload.drop_here': 'Drop your file here',
      'file_upload.click_to_upload': 'Click to upload or drag and drop',
      'file_upload.accepted_formats': 'Accepted formats: {formats}',
      'file_upload.all_formats_accepted': 'All file types accepted',
      'file_upload.max_size': 'Max size: {size}MB',
      'file_upload.remove_file': 'Remove file',
      'file_upload.file_size_error': 'File size must be less than {size}MB',
      'file_upload.file_type_error': 'Please select a valid file type: {types}',
      'file_upload.bytes': 'Bytes',
      'file_upload.kb': 'KB',
      'file_upload.mb': 'MB',
      'file_upload.gb': 'GB',
      
      // Subscriptions Management
      'subscriptions.title': 'Subscriptions Management',
      'subscriptions.subtitle': 'Manage supplier subscriptions and billing cycles',
      'subscriptions.add': 'Add Subscription',
      'subscriptions.edit': 'Edit Subscription',
      'subscriptions.create': 'Create New Subscription',
      'subscriptions.update': 'Update Subscription',
      'subscriptions.cancel': 'Cancel Subscription',
      'subscriptions.reactivate': 'Reactivate Subscription',
      'subscriptions.extend': 'Extend Subscription',
      'subscriptions.delete': 'Delete Subscription',
      'subscriptions.supplier': 'Supplier',
      'subscriptions.plan': 'Plan',
      'subscriptions.start_date': 'Start Date',
      'subscriptions.end_date': 'End Date',
      'subscriptions.price_per_month': 'Price per Month',
      'subscriptions.months': 'Number of Months',
      'subscriptions.status': 'Status',
      'subscriptions.requested_date': 'Requested Date',
      'subscriptions.actions': 'Actions',
      'subscriptions.total': 'Total Subscriptions',
      'subscriptions.active': 'Active',
      'subscriptions.expired': 'Expired',
      'subscriptions.cancelled': 'Cancelled',
      'subscriptions.inactive': 'Inactive',
      'subscriptions.monthly_revenue': 'Monthly Revenue',
      'subscriptions.all_subscriptions': 'All Subscriptions',
      'subscriptions.pending': 'Pending',
      'subscriptions.approved': 'Approved',
      'subscriptions.rejected': 'Rejected',
      'subscriptions.search_placeholder': 'Search subscriptions by supplier, plan, or email...',
      'subscriptions.loading': 'Loading subscriptions...',
      'subscriptions.loading_suppliers_plans': 'Loading suppliers and plans...',
      'subscriptions.no_subscriptions': 'No subscriptions found',
      'subscriptions.no_matches': 'No subscriptions match your current filters',
      'subscriptions.get_started': 'Get started with managing supplier subscriptions',
      'subscriptions.tip': 'Tip: Subscriptions allow you to manage supplier access to the platform and track billing cycles effectively.',
      'subscriptions.created': 'Subscription created successfully',
      'subscriptions.updated': 'Subscription updated successfully',
      'subscriptions.cancelled_success': 'Subscription cancelled successfully',
      'subscriptions.reactivated': 'Subscription reactivated successfully',
      'subscriptions.extended': 'Subscription extended successfully',
      'subscriptions.deleted': 'Subscription deleted successfully',
      'subscriptions.cancel_confirm': 'Are you sure you want to cancel this subscription?',
      'subscriptions.reactivate_confirm': 'Are you sure you want to reactivate this subscription?',
      'subscriptions.delete_confirm': 'Are you sure you want to delete this subscription? This action cannot be undone.',
      'subscriptions.extend_confirm': 'Are you sure you want to extend this subscription?',
      'subscriptions.select_supplier': 'Select a supplier',
      'subscriptions.select_plan': 'Select a plan',
      'subscriptions.subscription_details': 'Subscription Details',
      'subscriptions.date_and_duration': 'Date and Duration',
      'subscriptions.pricing': 'Pricing',
      'subscriptions.months_required': 'Number of months is required',
      'subscriptions.supplier_required': 'Supplier is required',
      'subscriptions.plan_required': 'Plan is required',
      'subscriptions.start_date_required': 'Start date is required',
      'subscriptions.end_date_required': 'End date is required',
      'subscriptions.price_required': 'Valid price is required',
      'subscriptions.end_date_after_start': 'End date must be after start date',
      'subscriptions.already_approved': 'Already approved',
      'subscriptions.already_rejected': 'Already rejected',
      'subscriptions.already_cancelled': 'Already cancelled',
      'subscriptions.showing': 'Showing {from} to {to} of {total} subscriptions',
      'subscriptions.create_description': 'Create a new subscription for a supplier',
      'subscriptions.update_description': 'Update subscription details and settings',
      
      // Plans Management
      'plans.title': 'Plans Management',
      'plans.subtitle': 'Create and manage subscription plans for suppliers',
      'plans.add': 'Add Plan',
      'plans.edit': 'Edit Plan',
      'plans.create': 'Create New Plan',
      'plans.update': 'Update Plan',
      'plans.delete': 'Delete Plan',
      'plans.name': 'Plan Name',
      'plans.name_ar': 'Plan Name (Arabic)',
      'plans.description': 'Description',
      'plans.description_ar': 'Description (Arabic)',
      'plans.max_clients': 'Max Clients',
      'plans.price_per_month': 'Price per Month',
      'plans.is_custom': 'Custom Plan',
      'plans.is_active': 'Active Plan',
      'plans.standard': 'Standard',
      'plans.custom': 'Custom',
      'plans.all_plans': 'All Plans',
      'plans.search_placeholder': 'Search plans by name...',
      'plans.loading': 'Loading plans...',
      'plans.no_plans': 'No plans found',
      'plans.no_matches': 'No plans match your current filters',
      'plans.get_started': 'Get started with managing subscription plans',
      'plans.created': 'Plan created successfully',
      'plans.updated': 'Plan updated successfully',
      'plans.deleted': 'Plan deleted successfully',
      'plans.delete_confirm': 'Are you sure you want to delete this plan?',
      'plans.delete_warning': 'This action cannot be undone.',
      'plans.name_required': 'Plan name is required',
      'plans.name_ar_required': 'Arabic plan name is required',
      'plans.price_required': 'Valid price is required',
      'plans.max_clients_min': 'Max clients must be at least 1',
      'plans.plan_details': 'Plan Details',
      'plans.plan_settings': 'Plan Settings',
      'plans.total_plans': 'Total Plans',
      'plans.active_plans': 'Active Plans',
      'plans.standard_plans': 'Standard Plans',
      'plans.custom_plans': 'Custom Plans',
      'plans.total_revenue': 'Total Revenue',
      
      // Subscription Requests
      'requests.title': 'Subscription Requests',
      'requests.subtitle': 'Review and manage subscription requests from suppliers',
      'requests.approve': 'Approve',
      'requests.reject': 'Reject',
      'requests.approve_request': 'Approve Request',
      'requests.reject_request': 'Reject Request',
      'requests.all_requests': 'All Requests',
      'requests.search_placeholder': 'Search requests by supplier, plan, or email...',
      'requests.loading': 'Loading requests...',
      'requests.no_requests': 'No subscription requests found',
      'requests.no_matches': 'No requests match your current filters',
      'requests.get_started': 'When suppliers request subscriptions, they will appear here for your review and approval.',
      'requests.approved_success': 'Subscription request approved successfully',
      'requests.rejected_success': 'Subscription request rejected successfully',
      'requests.approve_confirm': 'Are you sure you want to approve the subscription request for "{name}"?',
      'requests.reject_confirm': 'Are you sure you want to reject the subscription request for "{name}"? This action cannot be undone.',
      'requests.total_requests': 'Total Requests',
      'requests.today': 'Today',
      'requests.standard_plan': 'Standard Plan',
      'requests.custom_plan': 'Custom Plan',
      
      // Supplier Subscriptions
      'supplier_subscriptions.title': 'Subscription Management',
      'supplier_subscriptions.subtitle': 'Manage your subscription plans and requests',
      'supplier_subscriptions.current_subscription': 'Current Subscription',
      'supplier_subscriptions.available_plans': 'Available Plans',
      'supplier_subscriptions.subscription_requests': 'Subscription Requests',
      'supplier_subscriptions.current_status': 'Current Status',
      'supplier_subscriptions.current_plan': 'Current Plan',
      'supplier_subscriptions.monthly_price': 'Monthly Price',
      'supplier_subscriptions.per_month': 'per month',
      'supplier_subscriptions.subscription_details_description': 'View your current subscription details and status',
      'supplier_subscriptions.plans_description': 'Browse available subscription plans and their features',
      'supplier_subscriptions.requests_description': 'Create and manage your subscription requests',
      'supplier_subscriptions.no_active_subscription': 'No Active Subscription',
      'supplier_subscriptions.no_subscription_description': 'You currently don\'t have an active subscription. Browse available plans to get started.',
      'supplier_subscriptions.browse_plans': 'Browse Plans',
      'supplier_subscriptions.no_plan': 'No Plan',
      'supplier_subscriptions.detailed_information': 'Detailed Information',
      'supplier_subscriptions.subscription_id': 'Subscription ID',
      'supplier_subscriptions.duration': 'Duration',
      'supplier_subscriptions.plan_details': 'Plan Details',
      'supplier_subscriptions.plan_name': 'Plan Name',
      'supplier_subscriptions.total_cost': 'Total Cost',
      'supplier_subscriptions.plan_description': 'Plan Description',
      'supplier_subscriptions.browse_other_plans': 'Browse Other Plans',
      'supplier_subscriptions.request_renewal': 'Request Renewal',
      'supplier_subscriptions.no_plans_available': 'No Plans Available',
      'supplier_subscriptions.no_plans_description': 'There are currently no subscription plans available.',
      'supplier_subscriptions.custom_plan': 'Custom Plan',
      'supplier_subscriptions.view_details': 'View Details',
      'supplier_subscriptions.description': 'Description',
      'supplier_subscriptions.features': 'Features',
      'supplier_subscriptions.full_platform_access': 'Full Platform Access',
      'supplier_subscriptions.priority_support': 'Priority Support',
      'supplier_subscriptions.request_subscription': 'Request Subscription',
      'supplier_subscriptions.create_subscription_request': 'Create Subscription Request',
      'supplier_subscriptions.select_plan': 'Select Plan',
      'supplier_subscriptions.choose_plan': 'Choose a plan',
      'supplier_subscriptions.months_requested': 'Months Requested',
      'supplier_subscriptions.payment_proof': 'Payment Proof',
      'supplier_subscriptions.upload_payment_proof': 'Upload payment proof',
      'supplier_subscriptions.payment_proof_help': 'Upload a screenshot or PDF of your payment confirmation',
      'supplier_subscriptions.calculated_price': 'Calculated Price',
      'supplier_subscriptions.price_breakdown': '${monthly} × {months} months',
      'supplier_subscriptions.submit_request': 'Submit Request',
      'supplier_subscriptions.request_created_success': 'Subscription request created successfully',
      'supplier_subscriptions.pending_request_warning': 'You have a pending request',
      'supplier_subscriptions.pending_request_description': 'You already have a subscription request pending approval. Please wait for admin review.',
      'supplier_subscriptions.no_requests': 'No Requests',
      'supplier_subscriptions.no_requests_description': 'You haven\'t created any subscription requests yet.',
      'supplier_subscriptions.create_first_request': 'Create First Request',
      'supplier_subscriptions.create_request': 'Create Request',
      'supplier_subscriptions.unknown_plan': 'Unknown Plan',
      'supplier_subscriptions.requested_for': 'Requested for',
      'supplier_subscriptions.request_details': 'Request Details',
      'supplier_subscriptions.request_information': 'Request Information',
      'supplier_subscriptions.request_id': 'Request ID',
      'supplier_subscriptions.total_amount': 'Total Amount',
      'supplier_subscriptions.view_payment_proof': 'View Payment Proof',
      'supplier_subscriptions.admin_notes': 'Admin Notes',
      'supplier_subscriptions.plan_required': 'Please select a plan',
      'supplier_subscriptions.months_required': 'Please enter the number of months',
      'supplier_subscriptions.payment_proof_required': 'Please upload payment proof',
      'supplier_subscriptions.status': 'Status',
      'supplier_subscriptions.status_active': 'Active',
      'supplier_subscriptions.status_expired': 'Expired',
      'supplier_subscriptions.status_cancelled': 'Cancelled',
      'supplier_subscriptions.status_pending': 'Pending',
      'supplier_subscriptions.status_undefined': 'Undefined',
      'supplier_subscriptions.start_date': 'Start Date',
      'supplier_subscriptions.end_date': 'End Date',
      'supplier_subscriptions.remaining_days': 'Remaining Days',
      'supplier_subscriptions.days': 'days',
      'supplier_subscriptions.current_clients': 'Current Clients',
      'supplier_subscriptions.remaining_slots': 'Remaining Slots',
      'supplier_subscriptions.price_per_month': 'Price per Month',
      'supplier_subscriptions.max_clients': 'Max Clients',
    },
    ar: {
      // Admin Dashboard
      'admin.dashboard': 'لوحة تحكم المدير',
      'admin.categories': 'الفئات',
      'admin.areas': 'المناطق',
      'admin.governorates': 'المحافظات',
      'admin.administrators': 'المديرين',
      'admin.clients': 'العملاء',
      'admin.suppliers': 'الموردين',
      
      // Common
      'common.add': 'إضافة',
      'common.edit': 'تعديل',
      'common.delete': 'حذف',
      'common.save': 'حفظ',
      'common.cancel': 'إلغاء',
      'common.search': 'بحث',
      'common.loading': 'جاري التحميل...',
      'common.active': 'نشط',
      'common.inactive': 'غير نشط',
      'common.yes': 'نعم',
      'common.no': 'لا',
      'common.confirm': 'تأكيد',
      'common.back': 'رجوع',
      'common.next': 'التالي',
      'common.previous': 'السابق',
      'common.submit': 'إرسال',
      'common.close': 'إغلاق',
      'common.open': 'فتح',
      'common.refresh': 'تحديث',
      'common.export': 'تصدير',
      'common.import': 'استيراد',
      'common.download': 'تحميل',
      'common.upload': 'رفع',
      'common.view': 'عرض',
      'common.details': 'التفاصيل',
      'common.actions': 'الإجراءات',
      'common.status': 'الحالة',
      'common.name': 'الاسم',
      'common.email': 'البريد الإلكتروني',
      'common.phone': 'الهاتف',
      'common.address': 'العنوان',
      'common.created_at': 'تاريخ الإنشاء',
      'common.updated_at': 'تاريخ التحديث',
      'common.management': 'الإدارة',
      'common.retry': 'إعادة المحاولة',
      'common.user': 'المستخدم',
      'common.changes': 'التغييرات',
      'common.total': 'إجمالي',
      'common.showing': 'عرض {from} إلى {to} من {total}',
      
      // Search
      'search.placeholder': 'البحث...',
      
      // Profile
      'profile.failed_to_load': 'فشل في تحميل الملف الشخصي',
      'profile.logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'profile.logout': 'تسجيل الخروج',
      'profile.default_name': 'المدير',
      'profile.administrator': 'المدير',
      'profile.super_administrator': 'المدير الرئيسي',
      'profile.it_support': 'دعم التكنولوجيا',
      'profile.account_type': 'نوع الحساب',
      'profile.secure_admin_account': 'حساب المدير الآمن',
      
      // Categories
      'categories.title': 'إدارة الفئات',
      'categories.subtitle': 'إدارة المنتجات بالفئات وإدارة ظهورها',
      'categories.add': 'إضافة فئة',
      'categories.edit': 'تعديل الفئة',
      'categories.delete': 'حذف الفئة',
      'categories.name_en': 'اسم الفئة (الإنجليزية)',
      'categories.name_ar': 'اسم الفئة (العربية)',
      'categories.icon': 'الأيقونة',
      'categories.icon_required': 'الأيقونة مطلوبة',
      'categories.icon_optional': 'الأيقونة (اختيارية)',
      'categories.remove_icon': 'إزالة الأيقونة الحالية',
      'categories.active_category': 'فئة نشطة',
      'categories.inactive_categories_warning': 'الفئات غير النشطة لن تظهر في قوائم المنتجات',
      'categories.no_categories': 'لم يتم العثور على فئات',
      'categories.get_started': 'ابدأ بإنشاء فئتك الأولى',
      'categories.loading': 'جاري تحميل الفئات...',
      'categories.created': 'تم إنشاء الفئة!',
      'categories.updated': 'تم تحديث الفئة!',
      'categories.deleted': 'تم حذف الفئة!',
      'categories.delete_confirm': 'هل أنت متأكد من حذف هذه الفئة؟',
      'categories.delete_warning': 'لا يمكن التراجع عن هذا الإجراء.',
      
      // Areas
      'areas.title': 'إدارة المناطق',
      'areas.subtitle': 'إدارة مناطق التوصيل وحدودها الجغرافية',
      'areas.add': 'إضافة منطقة',
      'areas.edit': 'تعديل المنطقة',
      'areas.delete': 'حذف المنطقة',
      'areas.name': 'اسم المنطقة',
      'areas.governorate': 'المحافظة',
      'areas.polygon_points': 'نقاط المضلع',
      'areas.select_governorate': 'اختر محافظة لعرض المناطق',
      'areas.choose_governorate': 'اختر محافظة من القائمة المنسدلة أعلاه لرؤية مناطقها',
      'areas.no_areas': 'لم يتم العثور على مناطق',
      'areas.loading': 'جاري تحميل المناطق...',
      'areas.created': 'تم إنشاء المنطقة بنجاح!',
      'areas.updated': 'تم تحديث المنطقة بنجاح!',
      'areas.deleted': 'تم حذف المنطقة بنجاح!',
      'areas.delete_confirm': 'هل أنت متأكد من حذف هذه المنطقة؟',
      'areas.delete_warning': 'لا يمكن التراجع عن هذا الإجراء.',
      'areas.search_placeholder': 'البحث في المناطق بالاسم أو المحافظة...',
      'areas.all_governorates': 'جميع المحافظات',
      'areas.filter_by_governorate': 'تصفية حسب المحافظة',
      'areas.table_name': 'الاسم',
      'areas.table_governorate': 'المحافظة',
      'areas.table_polygon_points': 'نقاط المضلع',
      'areas.table_actions': 'الإجراءات',
      'areas.adding': 'جاري الإضافة...',
      
      // Form validation
      'validation.required': 'هذا الحقل مطلوب.',
      'validation.email': 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
      'validation.phone': 'يرجى إدخال رقم هاتف صحيح.',
      'validation.min_length': 'يجب أن يكون على الأقل {min} أحرف.',
      'validation.max_length': 'يجب أن يكون أقل من {max} أحرف.',
      'validation.password_requirements': 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل وتتضمن: حرف كبير، حرف صغير، رقم، ورمز خاص.',
      'validation.passwords_not_match': 'كلمات المرور غير متطابقة.',
      'validation.positive_number': 'يجب أن يكون رقماً موجباً.',
      'validation.percentage_range': 'يجب أن يكون بين 0-100.',
      'validation.image_required': 'الصورة مطلوبة.',
      'validation.image_type': 'يجب أن يكون الملف صورة.',
      'validation.file_size': 'يجب أن يكون الملف أقل من {size} ميجابايت.',
      
      // Messages
      'messages.success': 'نجح!',
      'messages.error': 'خطأ!',
      'messages.warning': 'تحذير!',
      'messages.info': 'معلومات',
      'messages.please_fix_errors': 'يرجى إصلاح الأخطاء في النموذج.',
      'messages.failed_to_submit': 'فشل في الإرسال',
      'messages.failed_to_load': 'فشل في تحميل البيانات',
      'messages.failed_to_delete': 'فشل في الحذف',
      'messages.failed_to_update': 'فشل في التحديث',
      'messages.failed_to_create': 'فشل في الإنشاء',
      'messages.operation_successful': 'تمت العملية بنجاح!',
      'messages.operation_failed': 'فشلت العملية. يرجى المحاولة مرة أخرى.',
      'messages.confirm_action': 'هل أنت متأكد من تنفيذ هذا الإجراء؟',
      'messages.unsaved_changes': 'لديك تغييرات غير محفوظة. هل أنت متأكد من المغادرة؟',
      'messages.something_went_wrong': 'حدث خطأ أثناء تحميل هذه الصفحة.',
      'messages.try_adjusting_filters': 'حاول تعديل البحث أو المرشحات',
      'messages.authentication_missing': 'رمز المصادقة مفقود',
      'messages.showing': 'عرض {from} إلى {to} من {total}',
      
      // Navigation
      'nav.dashboard': 'لوحة التحكم',
      'nav.categories': 'الفئات',
      'nav.areas': 'المناطق',
      'nav.governorates': 'المحافظات',
      'nav.administrators': 'المديرين',
      'nav.clients': 'العملاء',
      'nav.suppliers': 'الموردين',
      'nav.settings': 'الإعدادات',
      'nav.profile': 'الملف الشخصي',
      'nav.logout': 'تسجيل الخروج',
      
      // Administrators
      'administrators.title': 'إدارة المديرين',
      'administrators.subtitle': 'إدارة مديري النظام وصلاحياتهم',
      'administrators.add': 'إضافة مدير جديد',
      'administrators.edit': 'تعديل المدير',
      'administrators.delete': 'حذف المدير',
      'administrators.manage': 'إدارة المديرين',
      'administrators.role': 'الدور',
      'administrators.superadmin': 'مدير رئيسي',
      'administrators.admin': 'مدير',
      'administrators.loading': 'جاري تحميل المديرين...',
      'administrators.no_administrators': 'لم يتم العثور على مديرين',
      'administrators.get_started': 'ابدأ بإضافة أول مدير لك',
      'administrators.add_administrator': '+ إضافة مدير',
      'administrators.delete_confirm': 'حذف المدير {name}؟',
      'administrators.created': 'تم إنشاء المدير',
      'administrators.updated': 'تم تحديث المدير',
      'administrators.deleted': 'تم حذف المدير',
      
      // Suppliers
      'suppliers.title': 'إدارة الموردين',
      'suppliers.subtitle': 'إدارة حسابات الموردين وحالتهم',
      'suppliers.search_placeholder': 'البحث في الموردين بالاسم أو البريد الإلكتروني أو الهاتف...',
      'suppliers.all_statuses': 'جميع الحالات',
      'suppliers.pending': 'في الانتظار',
      'suppliers.rejected': 'مرفوض',
      'suppliers.approve': 'موافقة',
      'suppliers.reject': 'رفض',
      'suppliers.toggle_status': 'تبديل الحالة',
      'suppliers.verify_email': 'التحقق من البريد الإلكتروني',
      'suppliers.loading': 'جاري تحميل الموردين...',
      'suppliers.no_suppliers': 'لم يتم العثور على موردين',
      'suppliers.no_matches': 'لا يوجد موردين يطابقون المرشحات الحالية',
      'suppliers.approved': 'تمت الموافقة على المورد بنجاح',
      'suppliers.rejected_success': 'تم رفض المورد بنجاح',
      'suppliers.status_toggled': 'تم تبديل حالة المورد بنجاح',
      'suppliers.email_verified': 'تم التحقق من بريد المورد الإلكتروني بنجاح',
      'suppliers.deleted': 'تم حذف المورد بنجاح',
      'suppliers.approve_confirm': 'هل أنت متأكد من الموافقة على {name}؟',
      'suppliers.reject_confirm': 'هل أنت متأكد من رفض {name}؟',
      'suppliers.delete_confirm': 'هل أنت متأكد من حذف {name}؟ لا يمكن التراجع عن هذا الإجراء.',
      'suppliers.toggle_confirm': 'هل أنت متأكد من {action} {name}؟',
      'suppliers.activate': 'تفعيل',
      'suppliers.deactivate': 'إلغاء التفعيل',
      'suppliers.showing': 'عرض {from} إلى {to} من {total} مورد',
      'suppliers.page': 'الصفحة {current} من {total}',
      'suppliers.per_page': 'في الصفحة',
      
      // Governorates
      'governorates.title': 'المحافظات',
      'governorates.subtitle': 'عرض جميع المحافظات المتاحة في النظام',
      'governorates.view': 'عرض',
      'governorates.all_governorates': 'جميع المحافظات',
      'governorates.count': '{count} محافظة{plural}',
      'governorates.loading': 'جاري تحميل المحافظات...',
      'governorates.no_governorates': 'لم يتم العثور على محافظات',
      'governorates.id': 'الرقم التعريفي',
      
      // Form Fields
      'form.full_name': 'الاسم الكامل',
      'form.email_address': 'عنوان البريد الإلكتروني',
      'form.phone_number': 'رقم الهاتف',
      'form.password': 'كلمة المرور',
      'form.confirm_password': 'تأكيد كلمة المرور',
      'form.role': 'الدور',
      'form.select_role': 'اختر دوراً',
      'form.active_account': 'حساب نشط',
      'form.required': 'مطلوب',
      'form.optional': 'اختياري',
      
      // Form Validation Messages
      'form.name_required': 'الاسم مطلوب.',
      'form.name_min_length': 'يجب أن يكون الاسم على الأقل حرفين.',
      'form.name_max_length': 'يجب أن يكون الاسم أقل من 50 حرفاً.',
      'form.email_required': 'البريد الإلكتروني مطلوب.',
      'form.email_invalid': 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
      'form.phone_required': 'رقم الهاتف مطلوب.',
      'form.phone_invalid': 'يرجى إدخال رقم هاتف صحيح.',
      'form.password_required': 'كلمة المرور مطلوبة.',
      'form.password_requirements': 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل وتتضمن: حرف كبير، حرف صغير، رقم، ورمز خاص.',
      'form.confirm_password_required': 'تأكيد كلمة المرور مطلوب.',
      'form.passwords_not_match': 'كلمات المرور غير متطابقة.',
      'form.role_required': 'الدور مطلوب.',
      
      // Form Placeholders
      'form.placeholder.full_name': 'أدخل الاسم الكامل للمدير',
      'form.placeholder.email': 'أدخل عنوان البريد الإلكتروني',
      'form.placeholder.phone': 'أدخل رقم الهاتف (مثال: 01234567890)',
      'form.placeholder.password': 'أدخل كلمة مرور آمنة',
      'form.placeholder.confirm_password': 'أكد كلمة المرور',
      'form.placeholder.category_name_en': 'أدخل اسم الفئة بالإنجليزية',
      'form.placeholder.category_name_ar': 'أدخل اسم الفئة بالعربية',
      'form.placeholder.area_name': 'أدخل اسم المنطقة',
      
      // Form Actions
      'form.cancel': 'إلغاء',
      'form.create': 'إنشاء',
      'form.update': 'تحديث',
      'form.save': 'حفظ',
      'form.show_password': 'إظهار كلمة المرور',
      'form.hide_password': 'إخفاء كلمة المرور',
      
      // Modal Titles
      'modal.add_administrator': 'إضافة مدير جديد',
      'modal.edit_administrator': 'تعديل المدير',
      'modal.add_category': 'إضافة فئة جديدة',
      'modal.edit_category': 'تعديل الفئة',
      'modal.add_area': 'إضافة منطقة جديدة',
      'modal.edit_area': 'تعديل المنطقة',
      
      // Language
      'language.switch': 'تغيير اللغة',
      
      // Login
      'login.admin_title': 'تسجيل دخول المدير',
      'login.subtitle': 'الوصول إلى لوحة تحكم الإدارة',
      'login.email_label': 'عنوان البريد الإلكتروني *',
      'login.password_label': 'كلمة المرور *',
      'login.email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
      'login.password_placeholder': 'أدخل كلمة المرور',
      'login.sign_in': 'تسجيل الدخول',
      'login.signing_in': 'جاري تسجيل الدخول...',
      'login.need_help': 'تحتاج مساعدة؟ اتصل بمدير النظام',
      'login.secure_access': 'وصول آمن للمدير',
      'login.show_password': 'إظهار كلمة المرور',
      'login.hide_password': 'إخفاء كلمة المرور',
      'login.email_required': 'البريد الإلكتروني مطلوب.',
      'login.email_invalid': 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
      'login.password_required': 'كلمة المرور مطلوبة.',
      'login.password_min_length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
      'login.login_successful': 'تم تسجيل الدخول بنجاح! مرحباً بعودتك!',
      'login.login_failed': 'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد.',
      
      // Supplier Authentication
      'supplier_auth.login_title': 'تسجيل دخول المورد',
      'supplier_auth.register_title': 'تسجيل المورد',
      'supplier_auth.forgot_password_title': 'نسيت كلمة المرور',
      'supplier_auth.reset_password_title': 'إعادة تعيين كلمة المرور',
      'supplier_auth.verify_title': 'تحقق من حساب المورد',
      'supplier_auth.email_or_phone': 'البريد الإلكتروني أو الهاتف',
      'supplier_auth.email_or_phone_placeholder': 'أدخل بريدك الإلكتروني أو هاتفك',
      'supplier_auth.password': 'كلمة المرور',
      'supplier_auth.password_placeholder': 'أدخل كلمة المرور',
      'supplier_auth.confirm_password': 'تأكيد كلمة المرور',
      'supplier_auth.confirm_password_placeholder': 'أكد كلمة المرور',
      'supplier_auth.new_password': 'كلمة المرور الجديدة',
      'supplier_auth.new_password_placeholder': 'أدخل كلمة المرور الجديدة',
      'supplier_auth.confirm_new_password': 'تأكيد كلمة المرور',
      'supplier_auth.confirm_new_password_placeholder': 'أكد كلمة المرور الجديدة',
      'supplier_auth.reset_code': 'رمز إعادة التعيين',
      'supplier_auth.reset_code_placeholder': 'أدخل رمز إعادة التعيين',
      'supplier_auth.verification_code': 'رمز التحقق',
      'supplier_auth.verification_code_placeholder': 'أدخل الرمز الذي تلقيته',
      'supplier_auth.email_address': 'عنوان البريد الإلكتروني',
      'supplier_auth.email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
      'supplier_auth.name': 'الاسم',
      'supplier_auth.name_placeholder': 'اسم المورد',
      'supplier_auth.name_ar': 'الاسم (العربية)',
      'supplier_auth.name_ar_placeholder': 'اسم المورد بالعربية',
      'supplier_auth.email': 'البريد الإلكتروني',
      'supplier_auth.email_placeholder_register': 'بريد المورد الإلكتروني',
      'supplier_auth.phone': 'الهاتف',
      'supplier_auth.phone_placeholder': 'هاتف المورد',
      'supplier_auth.whatsapp': 'واتساب',
      'supplier_auth.whatsapp_placeholder': 'واتساب المورد',
      'supplier_auth.tax_card_number': 'رقم البطاقة الضريبية',
      'supplier_auth.tax_card_number_placeholder': 'رقم البطاقة الضريبية',
      'supplier_auth.cr_number': 'رقم السجل التجاري',
      'supplier_auth.cr_number_placeholder': 'رقم السجل التجاري',
      'supplier_auth.category': 'الفئة',
      'supplier_auth.select_category': 'اختر الفئة',
      'supplier_auth.loading_categories': 'جاري تحميل الفئات...',
      'supplier_auth.key_persons': 'الأشخاص الرئيسيون',
      'supplier_auth.key_person_name': 'الاسم',
      'supplier_auth.key_person_role': 'الدور',
      'supplier_auth.key_person_phone': 'الهاتف',
      'supplier_auth.key_person_email': 'البريد الإلكتروني',
      'supplier_auth.select_role': 'اختر الدور',
      'supplier_auth.management': 'الإدارة',
      'supplier_auth.accounting': 'المحاسبة',
      'supplier_auth.owner': 'المالك',
      'supplier_auth.logo': 'الشعار',
      'supplier_auth.tax_card_file': 'ملف البطاقة الضريبية',
      'supplier_auth.cr_file': 'ملف السجل التجاري',
      'supplier_auth.latitude': 'خط العرض',
      'supplier_auth.longitude': 'خط الطول',
      'supplier_auth.latitude_placeholder': 'سيتم اكتشاف خط العرض تلقائياً',
      'supplier_auth.longitude_placeholder': 'سيتم اكتشاف خط الطول تلقائياً',
      'supplier_auth.get_location': 'الحصول على الموقع الحالي',
      'supplier_auth.forgot_password_link': 'نسيت كلمة المرور؟',
      'supplier_auth.register_link': 'تسجيل',
      'supplier_auth.back_to_login': 'العودة لتسجيل الدخول',
      'supplier_auth.login_button': 'تسجيل الدخول',
      'supplier_auth.logging_in': 'جاري تسجيل الدخول...',
      'supplier_auth.register_button': 'تسجيل',
      'supplier_auth.registering': 'جاري التسجيل...',
      'supplier_auth.send_reset_link': 'إرسال رابط إعادة التعيين',
      'supplier_auth.sending': 'جاري الإرسال...',
      'supplier_auth.reset_password_button': 'إعادة تعيين كلمة المرور',
      'supplier_auth.resetting': 'جاري إعادة التعيين...',
      'supplier_auth.verify_button': 'تحقق',
      'supplier_auth.verifying': 'جاري التحقق...',
      'supplier_auth.resend_code': 'إعادة إرسال رمز التحقق',
      'supplier_auth.resending': 'جاري إعادة الإرسال...',
      'supplier_auth.forgot_password_description': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
      'supplier_auth.reset_password_description': 'أدخل رمز إعادة التعيين المرسل إلى بريدك الإلكتروني وكلمة المرور الجديدة.',
      'supplier_auth.password_requirements': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل مع حرف كبير وحرف صغير ورمز',
      'supplier_auth.login_successful': 'تم تسجيل الدخول بنجاح!',
      'supplier_auth.register_successful': 'تم تسجيل المورد بنجاح!',
      'supplier_auth.reset_link_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور!',
      'supplier_auth.reset_successful': 'تم إعادة تعيين كلمة المرور بنجاح!',
      'supplier_auth.verification_successful': 'تم التحقق بنجاح!',
      'supplier_auth.code_resent': 'تم إعادة إرسال رمز التحقق!',
      'supplier_auth.login_failed': 'فشل تسجيل الدخول',
      'supplier_auth.register_failed': 'فشل التسجيل',
      'supplier_auth.reset_link_failed': 'فشل في إرسال رابط إعادة التعيين',
      'supplier_auth.reset_failed': 'فشل في إعادة تعيين كلمة المرور',
      'supplier_auth.verification_failed': 'فشل التحقق',
      'supplier_auth.code_required': 'رمز إعادة التعيين مطلوب',
      'supplier_auth.password_confirmation_mismatch': 'تأكيد كلمة المرور غير متطابق',
      'supplier_auth.password_min_length': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
      'supplier_auth.password_uppercase': 'يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل',
      'supplier_auth.password_lowercase': 'يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل',
      'supplier_auth.password_symbol': 'يجب أن تحتوي كلمة المرور على رمز واحد على الأقل',
      'supplier_auth.email_required': 'البريد الإلكتروني مطلوب.',
      'supplier_auth.email_invalid': 'صيغة البريد الإلكتروني غير صحيحة.',
      'supplier_auth.name_ar_required': 'اسم المورد بالعربية مطلوب.',
      'supplier_auth.phone_required': 'الهاتف مطلوب.',
      'supplier_auth.phone_invalid': 'رقم الهاتف غير صحيح.',
      'supplier_auth.password_required': 'كلمة المرور مطلوبة.',
      'supplier_auth.password_min_6': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
      'supplier_auth.confirm_password_required': 'يرجى تأكيد كلمة المرور.',
      'supplier_auth.passwords_not_match': 'كلمات المرور غير متطابقة.',
      'supplier_auth.tax_card_required': 'رقم البطاقة الضريبية مطلوب.',
      'supplier_auth.cr_number_required': 'رقم السجل التجاري مطلوب.',
      'supplier_auth.category_required': 'الفئة مطلوبة.',
      'supplier_auth.logo_required': 'هذا الملف مطلوب.',
      'supplier_auth.logo_image': 'يجب أن يكون الشعار صورة.',
      'supplier_auth.file_image_pdf': 'يجب أن يكون الملف صورة أو PDF.',
      'supplier_auth.file_size': 'يجب أن يكون الملف أقل من 2 ميجابايت.',
      'supplier_auth.key_person_required': 'مطلوب.',
      'supplier_auth.key_person_email_invalid': 'البريد الإلكتروني غير صحيح.',
      'supplier_auth.key_person_phone_invalid': 'رقم الهاتف غير صحيح.',
      'supplier_auth.failed_load_categories': 'فشل في تحميل الفئات',
      
      // Client Authentication
      'client_auth.verify_title': 'تحقق من حسابك',
      'client_auth.email_or_phone': 'البريد الإلكتروني أو الهاتف',
      'client_auth.email_or_phone_placeholder': 'أدخل بريدك الإلكتروني أو هاتفك',
      'client_auth.verification_code': 'رمز التحقق',
      'client_auth.verification_code_placeholder': 'أدخل الرمز الذي تلقيته',
      'client_auth.verify_button': 'تحقق',
      'client_auth.verifying': 'جاري التحقق...',
      'client_auth.resend_code': 'إعادة إرسال رمز التحقق',
      'client_auth.resending': 'جاري إعادة الإرسال...',
      'client_auth.verification_successful': 'تم التحقق بنجاح!',
      'client_auth.verification_failed': 'فشل التحقق',
      'client_auth.code_resent': 'تم إعادة إرسال رمز التحقق!',
      'client_auth.login_title': 'تسجيل دخول العميل',
      'client_auth.password': 'كلمة المرور',
      'client_auth.password_placeholder': 'أدخل كلمة المرور',
      'client_auth.show_password': 'إظهار كلمة المرور',
      'client_auth.hide_password': 'إخفاء كلمة المرور',
      'client_auth.forgot_password': 'نسيت كلمة المرور؟',
      'client_auth.login_button': 'تسجيل الدخول',
      'client_auth.logging_in': 'جاري تسجيل الدخول...',
      'client_auth.login_successful': 'تم تسجيل الدخول بنجاح!',
      'client_auth.login_failed': 'فشل تسجيل الدخول',
      'client_auth.invitation_accepted': 'تم قبول الدعوة بنجاح!',
      'client_auth.invitation_failed': 'فشل في قبول الدعوة',
      'client_auth.invitation_invalid_expired': 'رابط الدعوة هذا غير صحيح أو منتهي الصلاحية. يرجى الاتصال بالمورد للحصول على دعوة جديدة.',
      'client_auth.register_title': 'تسجيل العميل',
      'client_auth.client_name': 'اسم العميل',
      'client_auth.client_name_placeholder': 'أدخل اسم العميل',
      'client_auth.phone_placeholder': 'أدخل رقم هاتفك',
      'client_auth.whatsapp_placeholder': 'أدخل رقم واتسابك',
      'client_auth.confirm_password': 'تأكيد كلمة المرور',
      'client_auth.confirm_password_placeholder': 'أكد كلمة المرور',
      'client_auth.tax_card_number_placeholder': 'أدخل رقم البطاقة الضريبية',
      'client_auth.cr_number_placeholder': 'أدخل رقم السجل التجاري',
      'client_auth.latitude_placeholder': 'سيتم اكتشاف خط العرض تلقائياً',
      'client_auth.longitude_placeholder': 'سيتم اكتشاف خط الطول تلقائياً',
      'client_auth.area_id': 'معرف المنطقة',
      'client_auth.area_id_placeholder': 'أدخل معرف المنطقة',
      'client_auth.registering': 'جاري التسجيل...',
      'client_auth.register_button': 'تسجيل',
      'client_auth.register_successful': 'تم التسجيل بنجاح!',
      'client_auth.register_failed': 'فشل التسجيل',
      'client_auth.passwords_not_match': 'كلمات المرور غير متطابقة',
      'client_auth.invitation_detected': 'تم اكتشاف دعوة!',
      'client_auth.invitation_auto_accept': 'بعد تسجيل الدخول، سيتم قبول دعوتك تلقائياً.',
      'client_auth.forgot_password_title': 'نسيت كلمة المرور',
      'client_auth.forgot_password_description': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
      'client_auth.email_address': 'عنوان البريد الإلكتروني',
      'client_auth.email_placeholder': 'أدخل عنوان بريدك الإلكتروني',
      'client_auth.email': 'البريد الإلكتروني',
      'client_auth.phone': 'رقم الهاتف',
      'client_auth.whatsapp': 'رقم الواتساب',
      'client_auth.tax_card_number': 'رقم البطاقة الضريبية',
      'client_auth.tax_card_file': 'ملف البطاقة الضريبية',
      'client_auth.cr_number': 'رقم السجل التجاري',
      'client_auth.cr_file': 'ملف السجل التجاري',
      'client_auth.latitude': 'خط العرض',
      'client_auth.longitude': 'خط الطول',
      'client_auth.get_location': 'الحصول على الموقع الحالي',
      'client_auth.send_reset_link': 'إرسال رابط إعادة التعيين',
      'client_auth.sending': 'جاري الإرسال...',
      'client_auth.reset_link_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور!',
      'client_auth.reset_link_failed': 'فشل في إرسال رابط إعادة التعيين',
      'client_auth.back_to_login': 'العودة لتسجيل الدخول',
      'client_auth.reset_password_title': 'إعادة تعيين كلمة المرور',
      'client_auth.reset_password_description': 'أدخل رمز إعادة التعيين المرسل إلى بريدك الإلكتروني وكلمة المرور الجديدة.',
      'client_auth.reset_code': 'رمز إعادة التعيين',
      'client_auth.reset_code_placeholder': 'أدخل رمز إعادة التعيين',
      'client_auth.new_password': 'كلمة المرور الجديدة',
      'client_auth.new_password_placeholder': 'أدخل كلمة المرور الجديدة',
      'client_auth.confirm_new_password': 'تأكيد كلمة المرور',
      'client_auth.confirm_new_password_placeholder': 'أكد كلمة المرور الجديدة',
      'client_auth.password_requirements': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل مع حرف كبير وحرف صغير ورمز',
      'client_auth.reset_password_button': 'إعادة تعيين كلمة المرور',
      'client_auth.resetting': 'جاري إعادة التعيين...',
      'client_auth.reset_successful': 'تم إعادة تعيين كلمة المرور بنجاح!',
      'client_auth.reset_failed': 'فشل في إعادة تعيين كلمة المرور',
      'client_auth.reset_code_required': 'رمز إعادة التعيين مطلوب',
      'client_auth.password_confirmation_mismatch': 'تأكيد كلمة المرور غير متطابق',
      'client_auth.password_min_length': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
      'client_auth.password_uppercase': 'يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل',
      'client_auth.password_lowercase': 'يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل',
      'client_auth.password_symbol': 'يجب أن تحتوي كلمة المرور على رمز واحد على الأقل',
      
      // Language
      'language.switch_to_english': 'التبديل إلى الإنجليزية',
      'language.switch_to_arabic': 'التبديل إلى العربية',
      
      // File Upload
      'file_upload.drop_here': 'أفلت الملف هنا',
      'file_upload.click_to_upload': 'انقر للرفع أو اسحب وأفلت',
      'file_upload.accepted_formats': 'الصيغ المقبولة: {formats}',
      'file_upload.all_formats_accepted': 'جميع أنواع الملفات مقبولة',
      'file_upload.max_size': 'الحد الأقصى للحجم: {size} ميجابايت',
      'file_upload.remove_file': 'إزالة الملف',
      'file_upload.file_size_error': 'يجب أن يكون حجم الملف أقل من {size} ميجابايت',
      'file_upload.file_type_error': 'يرجى اختيار نوع ملف صحيح: {types}',
      'file_upload.bytes': 'بايت',
      'file_upload.kb': 'كيلوبايت',
      'file_upload.mb': 'ميجابايت',
      'file_upload.gb': 'جيجابايت',
    }
  };

  const changeLanguage = (language) => {
    setCurrentLanguage(language);
    localStorage.setItem('app_language', language);
    // Set document direction for RTL languages
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  };

  const t = (key, params = {}) => {
    let translation = translations[currentLanguage][key] || translations.en[key] || key;
    
    // Replace parameters in translation
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    
    return translation;
  };

  useEffect(() => {
    // Set initial document direction
    document.documentElement.dir = currentLanguage === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    translations: translations[currentLanguage],
    isRTL: currentLanguage === 'ar'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 